version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-28

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "AndroidDemo/build.gradle" }}
          - v1-dependencies-

      - run: cd AndroidDemo;./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "AndroidDemo/build.gradle" }}


      - run: cd AndroidDemo;./gradlew assembleDebug
      - run: cd AndroidDemo;./gradlew assembleAndroidTest

      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
      - run: sudo gcloud config set project test-7d4cd
      - run: sudo gcloud auth activate-service-account firebase-adminsdk-ozzdp@test-7d4cd.iam.gserviceaccount.com --key-file ${HOME}/client-secret.json
      - run: sudo gcloud config set account firebase-adminsdk-ozzdp@test-7d4cd.iam.gserviceaccount.com
      - run: sudo gcloud firebase test android run --type instrumentation --app AndroidDemo/app/build/outputs/apk/debug/app-debug.apk --test AndroidDemo/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus9,version=25 --use-orchestrator